steps:
- name: maven:3-jdk-8
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mvn install:install-file -Dfile=xeger-1.0.jar -DgroupId=nl.flotsam -DartifactId=xeger -Dversion=1.0 -Dpackaging=jar
    mvn install:install-file -Dfile=artifactory-java-client-api-2.6.0.jar -DgroupId=artifactory-java-client -DartifactId=api -Dversion=2.6.0 -Dpackaging=jar
    mvn install:install-file -Dfile=artifactory-java-client-httpClient-2.6.0.jar -DgroupId=artifactory-java-client -DartifactId=httpClient -Dversion=2.6.0 -Dpackaging=jar
    mvn install:install-file -Dfile=artifactory-java-client-ning-services-2.5.1.jar -DgroupId=artifactory-java-client -DartifactId=ning-services -Dversion=2.5.1 -Dpackaging=jar
    mvn install:install-file -Dfile=artifactory-java-client-services-2.6.0.jar -DgroupId=artifactory-java-client -DartifactId=services -Dversion=2.6.0 -Dpackaging=jar
  volumes:
  - name: 'persistent_maven_repository'
    path: '/root/.m2/repository'
  dir: build/ext
- name: maven:3-jdk-8
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mvn test
  dir: core/java/iesi-core
  volumes:
  - name: 'persistent_maven_repository'
    path: '/root/.m2/repository'
- name: maven:3-jdk-8
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mvn -Dmaven.test.skip=true -P dependencies install project-info-reports:dependencies
  dir: core/java/iesi-core
  volumes:
  - name: 'persistent_maven_repository'
    path: '/root/.m2/repository'
- name: maven:3-jdk-8
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mvn test
  dir: core/java/iesi-rest-without-microservices
  volumes:
  - name: 'persistent_maven_repository'
    path: '/root/.m2/repository'
- name: maven:3-jdk-8
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p run/cache 
    mkdir -p metadata/gen 
    mvn -Dmaven.test.skip=true package project-info-reports:dependencies
  volumes:
  - name: 'persistent_maven_repository'
    path: '/root/.m2/repository'
  dir: core/java/iesi-rest-without-microservices
- name: maven:3-jdk-8
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    ls -lah
    java -cp target/iesi-core-0.6.0.jar:target/dependencies/* io.metadew.iesi.launch.AssemblyLauncher -repository ../../.. -sandbox ../../../sandbox -version 0.6.0 -instance build
  dir: core/java/iesi-core
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: 'bash'
  args:
  - -c
  - |
    apt-get install -y zip
    zip -r instance.zip sandbox/0.6.0/build
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo $BRANCH_NAME
    if [[ "$BRANCH_NAME" == "master" ]]; then
      echo "deploying to production environment"
    elif [[ "$BRANCH_NAME" == "develop" ]]; then
      echo "deploying to non-production environment"
    else
      echo "deploying to development environment"
    fi
artifacts:
  objects:
    location: 'gs://iesi-backend-artifacts'
    paths: ['instance.zip', 'core/java/iesi-rest-without-microservices/target/iesi-rest-0.6.0.jar', 'core/java/iesi-rest-without-microservices/target/iesi-rest-0.6.0.jar.original', 'core/java/iesi-core/target/iesi-core-0.6.0.jar']
# https://cloud.google.com/source-repositories/docs/quickstart-triggering-builds-with-source-repositories
# https://cloud.google.com/cloud-build/docs/build-config#volumes