server:
  disabled: false
  url: ldap://localhost:10389
  base: dc=example,dc=com
authentication:
  users:
    user-authenticate-attribute: cn
    user-search-attribute: cn
    user-search-base-dn: ou=users
  admin:
    dn: cn=khatth,ou=users,dc=example,dc=com
    password: khatth
groups-mapping:
  group-search-base-dn: ou=groups
  group-search-attribute: cn
  group-member-attribute: uniqueMember
  prefix: ''
  mapping-pairs:
    - iesi-name: iesi
      ad-name: All
    - iesi-name: B
      ad-name: Resource1
roles-mapping:
  mapping-pairs:
    - iesi-name: TEST_ENGINEER
      ad-name: testEngineer
    - iesi-name: TECHNICAL_ENGINEER
      ad-name: technicalEngineer