iesi:
  guard:
    authenticate: N
#  script:
#    execution:
#       runtime: ''
  server:
#    mode: off
    mode: standalone
    threads:
      timeout: 30
  home: ./iesi/core/java/iesi-core
  security:
    enabled: true
    jwt:
      secret: secret
      expiry-date: 10
  workers:
    - path: '.'
      timeout: 30
  master:
    path: '.'
    host: 'http://localhost:8080'
    credentials:
      user: admin
      password: admin