iesi:
  guard:
    authenticate: N
#  script:
#    execution:
#       runtime: ''
  server:
#    mode: off
    mode: standalone
    threads:
      timeout: 30
  home: '/home/hkhattabi/internship/iesi-sandboxes/0.7.0/PRTest'
  security:
    enabled: true
    jwt:
      secret: secret
      expiry-date: 10