# configurations related to the metadata repository
iesi:
  metadata:
    repository:
      # category can be: general, design, connectivity, trace, result.
      # each category should define its own type and definition
      - categories:
          - general
        instance:

        # type of database: sqlite, h2, mssql, netezza, oracle, postgresql
        coordinator:


#          type: sqlite
#         file: /home/robbe/IESISandbox/0.6.0/security/repository.db3


         type: sqlite
          file: /home/robbe/IESISandbox/0.6.0/develop/repository.db3

#          type: h2
#          mode: memory
#          database: test;ALIAS_COLUMN_NAME=TRUE
#          owner:
#            user: ""
#            password: ""

#          type: sqlite
#         file: 'C:/Users/tawbane.ouamar/Desktop/iesi-sandbox/0.6.0/IesiSecurityTest/repository.db3'
#          type: sqlite
#          file:

#          type: h2
#          mode: embedded
#          file:
#          schema:
#          host:
#          port:
#          owner:
#            user:
#            password:
#          reader:
#            user:
#            password:
#          writer:
#            user:
#            password:

#          type: mssql
#          database: 
#          host: 
#          port: 
#          schema: 
#          name: 
#          owner:
#            user:
#            password:
#          reader:
#            user:
#            password:
#          writer:
#            user:
#            password:

#          type: netezza
#          host: 
#          name: 
#          port: 
#          schema: 
#          owner:
#            user:
#            password:
#          reader:
#            user:
#            password:
#          writer:
#            user:
#            password:

#          type: postgresql
#          host: 
#          name: 
#          port: 
#          reader: 
#          schema: 
#          owner:
#            user:
#            password:
#          reader:
#            user:
#            password:
#          writer:
#            user:
#            password:

#          type: mysql
#          host:
#          name:
#          port:
#          schema:
#          owner:
#            user:
#            password:
#          reader:
#            user:
#            password:
#          writer:
#            user:
#            password: