iesi:
  guard:
    authenticate: N
  #  script:
  #    execution:
  #       runtime: ''
  server:
    #    mode: off
    mode: standalone
    threads:
      timeout: 30
  home: '.'
  security:
    enabled: true
    keystore:
      location: ""
      store-password: ""
      key-password: ""
    jwt:
      secret: secret
      expiry-date: 10
  workers:
    - path: '.'
      timeout: 30
  master:
    path: '.'
    host: 'http://localhost:8080'
    credentials:
      user: admin
      password: admin