# configurations related to the metadata repository
iesi:
  metadata:
    repository:
      # category can be: general, design, connectivity, trace, result.
      # each category should define its own type and definition
      - categories:
          - general

        # type of database: sqlite, h2, mssql, netezza, oracle, postgresql
        coordinator:
          # init_sql: alter  current....

          type: mysql
          host: localhost
          name: IESI
          port: 3306
          schema: IESI?useOldAliasMetadataBehavior=true&sessionVariables=sql_mode=ANSI_QUOTES
          owner:
            user: root
            password: iesi_root
#          reader:
#            user:
#            password:
#          writer:
#            user:
#            password:

#          type: sqlite
#          file: /home/robbe/IESISandbox/0.6.0/security/repository.db3

#          type: h2
#          mode: memory
#          database: test
#          owner:
#            user: test
#            password: test


#          type: oracle
#          schema:
#          connection: jdbc://test
#          owner:
#            user: owner
#            password: owner
#          reader:
#            user:
#            password:
#          writer:
#            user:
#            password:


#          type: h2
#          mode: embedded
#          file:
#          schema:
#          host:
#          port:
#          owner:
#            user:
#            password:
#          reader:
#            user:
#            password:
#          writer:
#            user:
#            password:

#          type: mssql
#          database: 
#          host: 
#          port: 
#          schema: 
#          name: 
#          owner:
#            user:
#            password:
#          reader:
#            user:
#            password:
#          writer:
#            user:
#            password:

#          type: netezza
#          host: 
#          name: 
#          port: 
#          schema: 
#          owner:
#            user:
#            password:
#          reader:
#            user:
#            password:
#          writer:
#            user:
#            password:

#          type: postgresql
#          host: 
#          name: 
#          port: 
#          schema:
#          owner:
#            user:
#            password:
#          reader:
#            user:
#            password:
#          writer:
#            user:
#            password:
