drop table users if exists;
create table users(
    username varchar_ignorecase(256) not null primary key,
    password varchar_ignorecase(256) not null,
    enabled boolean not null
);

drop table groups if exists;
create table groups (
    id bigint generated by default as identity(start with 0) primary key,
    group_name varchar_ignorecase(50) not null
);

drop table authorities if exists;
create table authorities (
    group_id bigint not null,
    authority varchar(50) not null,
    username VARCHAR(256) NOT NULL,
    constraint fk_authorities foreign key(group_id) references groups(id)
);