iesi:
  guard:
    authenticate: N
  #  script:
  #    execution:
  #       runtime: ''
  server:
    #    mode: off
    mode: standalone
    threads:
      timeout: 30
  workers:
    - path: '.'
  master:
    path: '.'
    host: 'http://localhost:8080'
    credentials:
      user: admin
      password: admin