CREATE TABLE IESI_AUD_SCRIPT
(
	ID				TEXT NOT NULL,
	USERNAME			TEXT NOT NULL,
	USER_ID				TEXT NOT NULL,
	ACTION				TEXT NOT NULL,
	TIMESTAMP		TEXT NOT NULL,
	SCRIPT_ID		TEXT NOT NULL,
	SCRIPT_NAME		TEXT NOT NULL,
	SCRIPT_VERSION		NUMERIC NOT NULL,
	SECURITY_GROUP		TEXT NOT NULL,
CONSTRAINT pk_IESI_AUD_SCRIPT PRIMARY KEY (ID)
);