
-- Adding Deleted_At COLUMN in DES_SCRIPT
ALTER TABLE DES_SCRIPT_LBL
DROP CONSTRAINT pk_IESI_DES_SCRIPT;

ALTER TABLE DES_SCRIPT_LBL 
ADD DELETED_AT varchar(255) NOT NULL
CONSTRAINT DEFAULT_VALUE DEFAULT 'NA'
WITH VALUES;

ALTER TABLE DES_SCRIPT_LBL
ADD CONSTANT pk_IESI_DES_SCRIPT_LBL PRIMARY KEY (SCRIPT_ID, DELETED_AT);

-- Adding Deleted_At COLUMN in DES_ACTION

ALTER TABLE DES_ACTION
DROP CONSTRAINT pk_IESI_DES_ACTION;

ALTER TABLE DES_ACTION 
ADD DELETED_AT varchar(255) NOT NULL
CONSTRAINT DEFAULT_VALUE DEFAULT 'NA'
WITH VALUES;

ALTER TABLE DES_ACTION
ADD CONSTANT pk_IESI_DES_ACTION PRIMARY KEY (SCRIPT_ID, SCRIPT_VRS_NB, ACTION_ID, DELETED_AT);

-- Adding Deleted_At COLUMN in DES_ACTION_PAR

ALTER TABLE DES_ACTION_PAR
DROP CONSTRAINT pk_IESI_DES_ACTION_PAR;

ALTER TABLE DES_ACTION_PAR 
ADD DELETED_AT varchar(255) NOT NULL
CONSTRAINT DEFAULT_VALUE DEFAULT 'NA'
WITH VALUES;

ALTER TABLE DES_ACTION_PAR
ADD CONSTANT pk_IESI_DES_ACTION_PAR PRIMARY KEY (SCRIPT_ID, SCRIPT_VRS_NB, ACTION_ID, ACTION_PAR_NM, DELETED_AT);

-- Adding Deleted_At COLUMN in DES_SCRIPT

ALTER TABLE DES_SCRIPT
DROP CONSTRAINT pk_IESI_DES_SCRIPT;

ALTER TABLE DES_SCRIPT 
ADD DELETED_AT varchar(255) NOT NULL
CONSTRAINT DEFAULT_VALUE DEFAULT 'NA'
WITH VALUES;

ALTER TABLE DES_SCRIPT
ADD CONSTANT pk_IESI_DES_SCRIPT PRIMARY KEY (SCRIPT_ID, DELETED_AT);

-- Adding Deleted_At COLUMN in DES_SCRIPT

ALTER TABLE DES_SCRIPT_PAR
DROP CONSTRAINT pk_IESI_DES_SCRIPT_PAR;

ALTER TABLE DES_SCRIPT_PAR 
ADD DELETED_AT varchar(255) NOT NULL
CONSTRAINT DEFAULT_VALUE DEFAULT 'NA'
WITH VALUES;

ALTER TABLE DES_SCRIPT_PAR
ADD CONSTANT pk_IESI_DES_SCRIPT_PAR PRIMARY KEY (SCRIPT_ID, SCRIPT_VRS_NB, SCRIPT_PAR_NM, DELETED_AT);

-- Adding Deleted_At COLUMN in DES_SCRIPT

ALTER TABLE DES_SCRIPT_VRS
DROP CONSTRAINT pk_IESI_DES_SCRIPT_VRS;

ALTER TABLE DES_SCRIPT_VRS 
ADD DELETED_AT varchar(255) NOT NULL
CONSTRAINT DEFAULT_VALUE DEFAULT 'NA'
WITH VALUES;

ALTER TABLE DES_SCRIPT_VRS
ADD CONSTANT pk_IESI_DES_SCRIPT_VRS PRIMARY KEY (SCRIPT_ID, SCRIPT_VRS_NB, DELETED_AT);