# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: maven
      - name: Install local dependencies
        run: |
          mvn install:install-file -Dfile=build/ext/xeger-1.0.jar -DgroupId=nl.flotsam -DartifactId=xeger -Dversion=1.0 -Dpackaging=jar
          mvn install:install-file -Dfile=build/ext/artifactory-java-client-api-2.6.0.jar -DgroupId=artifactory-java-client -DartifactId=api -Dversion=2.6.0 -Dpackaging=jar
          mvn install:install-file -Dfile=build/ext/artifactory-java-client-httpClient-2.6.0.jar -DgroupId=artifactory-java-client -DartifactId=httpClient -Dversion=2.6.0 -Dpackaging=jar
          mvn install:install-file -Dfile=build/ext/artifactory-java-client-ning-services-2.5.1.jar -DgroupId=artifactory-java-client -DartifactId=ning-services -Dversion=2.5.1 -Dpackaging=jar
          mvn install:install-file -Dfile=build/ext/artifactory-java-client-services-2.6.0.jar -DgroupId=artifactory-java-client -DartifactId=services -Dversion=2.6.0 -Dpackaging=jar
      - name: Fetch dependencies for core
        run: |
          cd core/java/iesi-core
          mvn dependency:go-offline
      - name: Build, package and install the core
        run: |
          cd core/java/iesi-core
          mvn clean install -Dmaven.deploy.skip=true -Dgpg.skip
      - name: Save test results
        run: |
          mkdir -p ~/test-results/junit/
          find core/java/iesi-core/target/surefire-reports/ -type f | grep -i xml$ | xargs -i cp {} ~/test-results/junit/
      - name: Store iesi-core artifact
        uses: actions/upload-artifact@v3
        with:
          name: iesi-core-0.10.0-SNAPSHOT.jar
          path: core/java/iesi-core/target/iesi-core-0.10.0-SNAPSHOT.jar
      - name: Store iesi-core executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: iesi-core-0.10.0-SNAPSHOT-exec.jar
          path: core/java/iesi-core/target/iesi-core-0.10.0-SNAPSHOT-exec.jar
    - name: Fetch dependencies for REST server
      run: |
        cd ~/repo/core/java/iesi-rest-without-microservices
        mvn dependency:go-offline
    - name: Build, package and install the REST server
      run:  |
        cd ~/repo/core/java/iesi-rest-without-microservices
        mvn clean install
    - name: Save test results
      run: |
        mkdir -p ~/test-results/junit/
        find core/java/iesi-rest-without-microservices/target/surefire-reports/ -type f | grep -i xml$ | xargs -i cp {} ~/test-results/junit/
    - name: Store iesi-rest artifact
      uses: actions/upload-artifact@v3
      with:
        name: iesi-rest-0.10.0-SNAPSHOT.jar
        path: core/java/iesi-rest-without-microservices/target/iesi-rest-0.10.0-SNAPSHOT.jar
    - name: Build assembly
      run: |
        cd core/java/iesi-core
        mvn -P dependencies validate project-info-reports:dependencies
        cd core/java/iesi-rest-without-microservices
        mvn project-info-reports:dependencies
        cd core/java/iesi-core/target
        java -jar iesi-core-0.10.0-SNAPSHOT-exec.jar -launcher assembly -repository ~/repo -sandbox ~/sandbox -instance assembly -version 0.10.0-SNAPSHOT


